/**
 * Evidence base — every entry fetched from the Crossref API and each DOI
 
*
 
r
e
-
v
e
r
i
f
i
e
d
 
b
y
 
d
i
r
e
c
t
 
r
e
s
o
l
u
t
i
o
n
 
o
n
 
2
0
2
6
-
0
9
-
1
3
 
(
m
e
t
a
d
a
t
a
 
c
o
p
i
e
d
 
v
e
r
b
a
t
i
m
)
.
 * Generated by _work/nic3/make_evidence.py — do not hand-edit entries.
 */

export interface EvidenceItem {
  doi: string; title: string; journal: string; year: number | null;
  authors: string[]; citedBy: number; group: string;
}

export const EVIDENCE: EvidenceItem[] = [
  { doi: '10.1016/j.jclepro.2016.12.048', title: 'The Circular Economy – A new sustainability paradigm?', journal: 'Journal of Cleaner Production', year: 2017, authors: ['Martin Geissdoerfer', 'Paulo Savaget', 'Nancy M.P. Bocken'], citedBy: 7922, group: 'circular economy' },
  { doi: '10.1016/j.resconrec.2017.09.005', title: 'Conceptualizing the circular economy: An analysis of 114 definitions', journal: 'Resources, Conservation and Recycling', year: 2017, authors: ['Julian Kirchherr', 'Denise Reike', 'Marko Hekkert'], citedBy: 7289, group: 'circular economy' },
  { doi: '10.1016/j.jclepro.2008.04.020', title: 'From a literature review to a conceptual framework for sustainable supply chain management', journal: 'Journal of Cleaner Production', year: 2008, authors: ['Stefan Seuring', 'Martin Müller'], citedBy: 4930, group: 'sustainable supply chain' },
  { doi: '10.3390/su131910496', title: 'Blockchain-Enabled Supply Chain Traceability in the Textile and Apparel Supply Chain: A Case Study of the Fiber Producer, Lenzing', journal: 'Sustainability', year: 2021, authors: ['Wafaa A. H. Ahmed', 'Bart L. MacCarthy'], citedBy: 94, group: 'traceability technology' },
  { doi: '10.1007/s42824-025-00190-9', title: 'Enhancing the Circular Economy in Textile Fiber Waste Recycling', journal: 'Materials Circular Economy', year: 2025, authors: ['Faheem Uddin'], citedBy: 4, group: 'circularity & recycling' },
  { doi: '10.54648/bula2024009', title: 'The Digital Product Passport of the Ecodesign Regulation - Passport to a Successful Twin Transformation in Product Law?', journal: 'Business Law Review', year: 2024, authors: ['Anne-Christin Mittwoch'], citedBy: 4, group: 'DPP & regulation' },
  { doi: '10.1007/s11356-026-37563-9', title: 'Environmental impact of open burning of polyester and cotton textile waste: a comparative analysis', journal: 'Environmental Science and Pollution Research', year: 2026, authors: ['Jeyran Bayramova', 'Steven Pires', 'Patricia A. Holden'], citedBy: 2, group: 'textile waste impact' },
  { doi: '10.55845/joce-2025-32212', title: 'Digital Product Passport: A Digital Catalyst for a Circular Transformation', journal: 'Journal of Circular Economy', year: 2026, authors: ['Katrin Dietrich', 'Tassilo Schuster', 'Lydia Bühler'], citedBy: 2, group: 'DPP & regulation' },
  { doi: '10.1007/s43615-026-00844-z', title: 'Reclaiming Waste: Informal Circularity in Bangladesh and the Struggle for Green Value in the Apparel Value Chain', journal: 'Circular Economy and Sustainability', year: 2026, authors: ['Lone Riisgaard'], citedBy: 1, group: 'Bangladesh circularity' },
  { doi: '10.1007/s43615-026-01000-3', title: 'Digital Product Passport for Circular Economy: A Review of Semantic Web Vocabularies and Requirements for Interoperability', journal: 'Circular Economy and Sustainability', year: 2026, authors: ['Kévin Boutillier'], citedBy: 1, group: 'DPP & regulation' },
  { doi: '10.30657/pea.2026.32.13', title: 'The Integration of RFID and Blockchain Technology for the Supply Chain Traceability of Durians', journal: 'Production Engineering Archives', year: 2026, authors: ['Karin Kandananond'], citedBy: 1, group: 'traceability technology' },
  { doi: '10.58753/jbspust.4.1.2023.21', title: 'The Impact of Social Compliance Practices on the Ready-Made Garment Industry in Bangladesh', journal: 'Journal of Business Studies', year: 2023, authors: ['Md. Mahabub Alam', 'Md. Shawan Uddin', 'Md. Sohel Rana'], citedBy: 1, group: 'Bangladesh RMG compliance' },
  { doi: '10.1787/df7dc9d4-en', title: 'A cut above: A guide to improving due diligence in garments and footwear supply chains', journal: 'OECD Observer', year: 2019, authors: ['Juliet Lawal'], citedBy: 1, group: 'due diligence & buyers' },
  { doi: '10.31881/tlr.2026.1234', title: 'A Sustainable Product Tracking System under the Combination of Textile Label Regulations and Digital Product Passport', journal: 'Textile & Leather Review', year: 2026, authors: ['Xuejie Zhao'], citedBy: 0, group: 'DPP & tracking' },
  { doi: '10.55845/joce-2026-41321', title: 'Enabling Sustainability Through Ecodesign and Recyclability in the Textile Industry: Understanding Material Compositions of Denim', journal: 'Journal of Circular Economy', year: 2026, authors: ['Tanita Behrendt', 'Elisabeth Eppinger', 'Erika Zernickel'], citedBy: 0, group: 'DPP & regulation' },
  { doi: '10.3989/ic.7377', title: 'Digital Product Logbook, the missing piece in the European Digital Product Passport puzzle', journal: 'Informes de la Construcción', year: 2026, authors: ['Aitor Aragón', 'Vincenzo Daponte'], citedBy: 0, group: 'DPP & regulation' },
];
